---
repos:
  - repo: https://github.com/python/black
    rev: 23.12.1
    hooks:
      - id: black
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=linz
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          - '--per-file-ignores=*/__init__.py:F401'
          - --ignore=E203, W503
          - --max-complexity=30
          - --max-line-length=456
          - --show-source
          - --statistics
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
#  - repo: https://github.com/pycqa/pydocstyle
#    rev: 6.1.1
#    hooks:
#      - id: pydocstyle
#        args:
#          - --source
#          - --explain
#          - --convention=google
#        additional_dependencies: ["toml"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: ["--py37-plus"]
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: node
        pass_filenames: false
        types: [python]
        additional_dependencies: ["pyright"]
        args:
          - --project=pyproject.toml
